package com.liskovsoft.smartyoutubetv2.common.exoplayer.selector.track;

import com.liskovsoft.sharedutils.helpers.Helpers;
import com.liskovsoft.youtubeapi.videoinfo.models.TranslatedCaptionTrack;

import java.util.regex.Pattern;

public class SubtitleTrack extends MediaTrack {
    private static final Pattern TRIM_PATTERN1 = Pattern.compile(" \\(.*\\) - .*");
    private static final Pattern TRIM_PATTERN2 = Pattern.compile(" - .*");
    private static final Pattern MARKER_PATTERN = Pattern.compile(".$");

    public SubtitleTrack(int rendererIndex) {
        super(rendererIndex);
    }

    /**
     * Remove autogenerated and other stuff
     */
    public static String trim(String language) {
        if (language == null) {
            return null;
        }

        return trimMarker(Helpers.replace(Helpers.replace(language, TRIM_PATTERN1, ""), TRIM_PATTERN2, "")); // english - us bla -> english
    }

    public static String trimIfAuto(String language) {
        return isAuto(language) ? trim(language) : language;
    }

    /**
     * Removes auto translate marker
     */
    private static String trimMarker(String language) {
        if (language != null && language.endsWith(TranslatedCaptionTrack.TRANSLATE_MARKER)) {
            return Helpers.replace(language, MARKER_PATTERN, "");
        } else {
            return language;
        }
    }

    public static boolean isAuto(String language) {
        return hasMarker(language);
    }

    private static boolean hasMarker(String language) {
        return language != null && language.endsWith(TranslatedCaptionTrack.TRANSLATE_MARKER);
    }
}
