#!/usr/bin/env python3
"""Run the existing whole-app shaper on loopback for USB adb-reverse tests."""

import argparse
import asyncio
import importlib.util
from pathlib import Path
import sys


async def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--port', type=int, default=18380)
    parser.add_argument('--control', type=int, default=18381)
    parser.add_argument('--down-kbps', type=float, default=0)
    parser.add_argument('--up-kbps', type=float, default=0)
    parser.add_argument('--rtt-ms', type=float, default=0)
    args = parser.parse_args()
    # Do not leave generated bytecode in the shared checkout.
    sys.dont_write_bytecode = True
    spec = importlib.util.spec_from_file_location('netshape', Path(__file__).with_name('netshape.py'))
    netshape = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(netshape)
    shape = netshape.Shape(args.down_kbps, args.up_kbps, args.rtt_ms)
    stats = netshape.Stats()
    proxy = netshape.Proxy(shape, stats, False)
    server = await asyncio.start_server(proxy.handle, '127.0.0.1', args.port)
    control = await asyncio.start_server(
        lambda reader, writer: netshape.control_handler(reader, writer, shape, stats),
        '127.0.0.1', args.control)
    print(f'netshape loopback proxy={args.port} control={args.control} {shape.describe()}', flush=True)
    async with server, control:
        await asyncio.gather(server.serve_forever(), control.serve_forever())


if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
